declare module "@mdx-js/react"
declare module "@ngsctt/remark-smartypants"
declare module "fs-readdir-recursive"
declare module "mdx-prism"
declare module "next-mdx-remote/*"
declare module "react-codepen-embed"
declare module "react-katex"
declare module "react-script-tag"
declare module "rehype-slug"
declare module "remark-abbr"

declare module "*.frag"
declare module "*.glsl"
declare module "*.vert"
